[theme]
primaryColor = "#FF7000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#1F1F1F"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false